name: Publish Docker Image

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: docker.io
  IMAGE_NAME: officialmoadel/quepasa
  GIT_REF: ${{ github.head_ref || github.ref_name }}
  NODE_ENV: production
  APP_ENV: production
  QUEPASA_CONTAINER_NAME: "quepasa"
  QUEPASA_HOST_NAME: "quepasa"
  QUEPASA_MEMORY_LIMIT: 512M
  QUEPASA_EXTERNAL_PORT: 31000
  QUEPASA_INTERNAL_PORT: 31000
  WEBAPIPORT: 31000
  QUEPASA_BASIC_AUTH_USER: ${{ secrets.DOCKER_USERNAME }}
  QUEPASA_BASIC_AUTH_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MIGRATIONS: "./migrations"
  WEBSOCKETSSL: false

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx # ✅ Fix: Enable multi-platform support
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=schedule
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64 # ✅ Multi-arch build enabled
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
